language: objective-c
osx_image: xcode7.3
rvm: system
install:
  # Travis comes with Postgres 9.4 data, so we much clear it out
  - rm -rf /usr/local/var/postgres
  # We must uninstall postgres for the install to reinitialize data
  - brew uninstall --force postgres

  - export GEM_HOME=tmp/ruby/2.0.0
  - export GEM_PATH=tmp/ruby/2.0.0
  - export PATH=${GEM_HOME}/bin:${PATH}
  - gem install bundler --no-document
  - bundle install
script:
  - bundle exec rake ci
